
import { Gender, HairstyleOption, Language } from './types';

export const HAIRSTYLE_OPTIONS: HairstyleOption[] = [
  // Original Styles
  {
    id: 'long-wavy-blonde',
    label: { en: 'Long Wavy Blonde', zh: '波浪金发' },
    prompt: 'long, wavy blonde hair with volume',
    description: { en: 'Long, wavy blonde hair with volume', zh: '蓬松的金色长卷发' },
    gender: [Gender.FEMALE],
    previewColor: 'bg-yellow-200',
  },
  {
    id: 'bob-cut-brunette',
    label: { en: 'Chic Bob Cut', zh: '时尚波波头' },
    prompt: 'a sharp, chin-length dark brunette bob cut',
    description: { en: 'A sharp, chin-length dark brunette bob cut', zh: '利落的深褐色齐下巴波波头' },
    gender: [Gender.FEMALE],
    previewColor: 'bg-stone-700',
  },
  {
    id: 'pixie-platinum',
    label: { en: 'Platinum Pixie', zh: '铂金精灵短发' },
    prompt: 'a short, modern platinum blonde pixie cut',
    description: { en: 'A short, modern platinum blonde pixie cut', zh: '现代感十足的铂金短发' },
    gender: [Gender.FEMALE],
    previewColor: 'bg-slate-200',
  },
  {
    id: 'red-layers',
    label: { en: 'Red Layered', zh: '红色层次长发' },
    prompt: 'long, layered vibrant red hair',
    description: { en: 'Long, layered vibrant red hair', zh: '层次分明的亮红色长发' },
    gender: [Gender.FEMALE],
    previewColor: 'bg-red-400',
  },
  {
    id: 'bangs-black',
    label: { en: 'Straight with Bangs', zh: '齐刘海黑长直' },
    prompt: 'long straight black hair with blunt bangs',
    description: { en: 'Long straight black hair with blunt bangs', zh: '黑色长直发配齐刘海' },
    gender: [Gender.FEMALE],
    previewColor: 'bg-neutral-900',
  },
  // New Styles
  {
    id: 'afro-natural',
    label: { en: 'Natural Afro', zh: '自然爆炸头' },
    prompt: 'a voluminous, natural textured afro hairstyle',
    description: { en: 'Voluminous natural afro texture', zh: '蓬松自然的爆炸头纹理' },
    gender: [Gender.MALE, Gender.FEMALE],
    previewColor: 'bg-stone-800',
  },
  {
    id: 'braids-cornrows',
    label: { en: 'Cornrows', zh: '地垄沟辫' },
    prompt: 'intricate cornrow braids close to the scalp',
    description: { en: 'Intricate braided cornrows', zh: '紧贴头皮的精致地垄沟编发' },
    gender: [Gender.MALE, Gender.FEMALE],
    previewColor: 'bg-neutral-800',
  },
  {
    id: 'hime-cut',
    label: { en: 'Hime Cut', zh: '姬发式' },
    prompt: 'a traditional Japanese Hime cut with cheek-length sidelocks and bangs',
    description: { en: 'Straight hair with cheek-length sidelocks', zh: '脸颊两侧平剪的姬发式' },
    gender: [Gender.FEMALE],
    previewColor: 'bg-neutral-900',
  },
  {
    id: 'pink-bob',
    label: { en: 'Neon Pink Bob', zh: '荧光粉波波头' },
    prompt: 'a vibrant neon pink bob cut',
    description: { en: 'Eye-catching neon pink short hair', zh: '吸睛的荧光粉色短发' },
    gender: [Gender.FEMALE],
    previewColor: 'bg-pink-400',
  },
  {
    id: 'rainbow-waves',
    label: { en: 'Rainbow Waves', zh: '彩虹卷发' },
    prompt: 'long wavy hair dyed in pastel rainbow colors',
    description: { en: 'Long hair with multi-colored pastel rainbow hues', zh: '梦幻的彩虹色长卷发' },
    gender: [Gender.FEMALE],
    previewColor: 'bg-gradient-to-r from-pink-300 via-purple-300 to-blue-300',
  },
  {
    id: 'blue-undercut',
    label: { en: 'Blue Undercut', zh: '蓝色铲青' },
    prompt: 'an edgy undercut dyed electric blue',
    description: { en: 'Short edgy style with electric blue color', zh: '前卫的电光蓝铲青' },
    gender: [Gender.MALE, Gender.FEMALE],
    previewColor: 'bg-blue-500',
  },
  // Men's / Short Styles
  {
    id: 'undercut-modern',
    label: { en: 'Modern Undercut', zh: '现代铲青' },
    prompt: 'a stylish undercut with textured top hair',
    description: { en: 'A stylish undercut with textured top hair', zh: '两侧铲青，顶部有纹理' },
    gender: [Gender.MALE, Gender.FEMALE],
    previewColor: 'bg-gray-400',
  },
  {
    id: 'buzz-cut',
    label: { en: 'Buzz Cut', zh: '寸头' },
    prompt: 'a clean, very short buzz cut',
    description: { en: 'A clean, very short buzz cut', zh: '干练的超短寸头' },
    gender: [Gender.MALE],
    previewColor: 'bg-stone-300',
  },
  {
    id: 'pompadour',
    label: { en: 'Classic Pompadour', zh: '经典背头' },
    prompt: 'a classic high-volume pompadour hairstyle',
    description: { en: 'A classic high-volume pompadour hairstyle', zh: '经典的高蓬松度背头' },
    gender: [Gender.MALE],
    previewColor: 'bg-amber-800',
  },
  {
    id: 'curly-top',
    label: { en: 'Curly Fade', zh: '卷发渐层' },
    prompt: 'short sides with a curly textured top',
    description: { en: 'Short sides with a curly textured top', zh: '两侧渐层，顶部卷发' },
    gender: [Gender.MALE],
    previewColor: 'bg-neutral-800',
  },
  {
    id: 'silver-fox',
    label: { en: 'Silver Flow', zh: '银色中长发' },
    prompt: 'medium length flowy silver hair',
    description: { en: 'Medium length flowy silver hair', zh: '飘逸的银色中长发' },
    gender: [Gender.MALE],
    previewColor: 'bg-gray-300',
  },
  {
    id: 'mullet-80s',
    label: { en: 'Retro Mullet', zh: '复古鲻鱼头' },
    prompt: 'a retro 80s style mullet hairstyle',
    description: { en: 'Business in the front, party in the back', zh: '前短后长的复古鲻鱼头' },
    gender: [Gender.MALE],
    previewColor: 'bg-orange-800',
  },
  {
    id: 'mohawk-punk',
    label: { en: 'Punk Mohawk', zh: '朋克莫霍克' },
    prompt: 'a tall, spiked punk mohawk',
    description: { en: 'Bold spiked strip of hair', zh: '大胆的直立莫霍克发型' },
    gender: [Gender.MALE],
    previewColor: 'bg-purple-900',
  },
  {
    id: 'dreadlocks',
    label: { en: 'Dreadlocks', zh: '脏辫' },
    prompt: 'medium length dreadlocks',
    description: { en: 'Styled dreadlocks', zh: '有型的脏辫' },
    gender: [Gender.MALE],
    previewColor: 'bg-neutral-700',
  },
  {
    id: 'viking-braids',
    label: { en: 'Viking Braids', zh: '维京编发' },
    prompt: 'long hair with warrior braids in a viking style',
    description: { en: 'Rugged braided viking style', zh: '粗犷的维京战士编发' },
    gender: [Gender.MALE],
    previewColor: 'bg-yellow-700',
  },
  {
    id: 'bald-clean',
    label: { en: 'Clean Shaven', zh: '光头' },
    prompt: 'completely bald, clean shaven head',
    description: { en: 'Completely bald head', zh: '完全光头造型' },
    gender: [Gender.MALE],
    previewColor: 'bg-orange-100',
  }
];

export const RANDOM_COMPONENTS = {
  lengths: [
    { en: 'very short', zh: '超短' },
    { en: 'chin-length', zh: '齐下巴' },
    { en: 'shoulder-length', zh: '齐肩' },
    { en: 'long', zh: '长' },
    { en: 'waist-length', zh: '齐腰长' }
  ],
  textures: [
    { en: 'pin-straight', zh: '笔直' },
    { en: 'wavy', zh: '微卷' },
    { en: 'curly', zh: '卷' },
    { en: 'coily', zh: '螺旋卷' },
    { en: 'messy', zh: '凌乱' },
    { en: 'sleek', zh: '柔顺' }
  ],
  colors: [
    { en: 'neon pink', zh: '荧光粉' },
    { en: 'icy blue', zh: '冰蓝色' },
    { en: 'emerald green', zh: '祖母绿' },
    { en: 'rainbow', zh: '彩虹色' },
    { en: 'platinum silver', zh: '铂金银' },
    { en: 'jet black', zh: '乌黑' },
    { en: 'chestnut brown', zh: '栗棕色' },
    { en: 'pastel purple', zh: '淡紫色' },
    { en: 'fiery red', zh: '火红色' },
    { en: 'golden blonde', zh: '金黄' },
    { en: 'rose gold', zh: '玫瑰金' }
  ],
  styles: [
    { en: 'bob cut', zh: '波波头' },
    { en: 'shag cut', zh: '碎发' },
    { en: 'layered cut', zh: '层次剪' },
    { en: 'ponytail', zh: '马尾' },
    { en: 'wolf cut', zh: '狼尾头' },
    { en: 'pixie cut', zh: '精灵短发' }
  ]
};

export const UI_TEXT: Record<Language, Record<string, string>> = {
  en: {
    title: 'HairSwap AI',
    subtitle: 'Powered by Gemini 2.5',
    heroTitle: 'Find your perfect hairstyle instantly.',
    heroDesc: 'Upload a photo, choose a style, and let AI show you exactly how you\'d look with a new cut or color.',
    step1: '1. Your Photo',
    step2: '2. Choose Transformation',
    uploadTitle: 'Upload your photo',
    uploadDesc: 'Drag and drop your image here, or click to browse. Front-facing photos work best.',
    uploadBtn: 'Select File',
    changePhoto: 'Change Photo',
    selectStyleHeader: 'Select a Style',
    randomStyle: 'Surprise Me (AI Random)',
    randomTip: 'Generates a completely unique style!',
    generateBtn: 'Generate Transformation',
    generatingBtn: 'Generating Look...',
    errorGeneric: 'Failed to generate image. Please try again or check if the image is valid.',
    resultsTitle: 'Your Results',
    favoritesTitle: 'My Favorites',
    resultsCount: 'style(s) generated',
    noResultsTitle: 'No styles generated yet',
    noResultsDesc: 'Select your photo and a hairstyle on the left to see the magic happen here.',
    noFavoritesDesc: 'You haven\'t saved any styles yet. Click the heart icon on a result to save it!',
    resultLabel: 'Result',
    compareLabel: 'Before / After',
    compareTip: 'Drag the slider to compare.',
    downloadBtn: 'Download Image',
    randomLabel: 'Mystery Style',
    randomDesc: 'A unique, AI-generated random hairstyle.',
    tabPresets: 'Presets',
    tabCustom: 'Text Input',
    tabReference: 'Reference Image',
    customPromptPlaceholder: 'Describe the hairstyle you want... e.g., "Short curly red hair with bangs" or "Cyberpunk neon spikes"',
    customPromptLabel: 'Hairstyle Description',
    refImageLabel: 'Upload Reference Image',
    refImageDesc: 'Upload a photo of the hairstyle you want to copy.',
    refImageBtn: 'Select Reference',
    viewResults: 'View Latest',
    viewFavorites: 'View Favorites',
  },
  zh: {
    title: 'AI 换发型',
    subtitle: '由 Gemini 2.5 驱动',
    heroTitle: '瞬间找到最适合你的发型',
    heroDesc: '上传照片，选择发型，让 AI 为你展示全新的剪裁或发色效果。',
    step1: '1. 上传照片',
    step2: '2. 选择变换方式',
    uploadTitle: '上传你的照片',
    uploadDesc: '拖拽图片到此处，或点击浏览。正面清晰照片效果最佳。',
    uploadBtn: '选择文件',
    changePhoto: '更换照片',
    selectStyleHeader: '选择发型',
    randomStyle: '随机盲盒 (AI生成)',
    randomTip: '生成完全独一无二的发型！',
    generateBtn: '立即生成',
    generatingBtn: '正在生成中...',
    errorGeneric: '生成失败，请重试或检查图片是否有效。',
    resultsTitle: '生成结果',
    favoritesTitle: '我的收藏',
    resultsCount: '个发型已生成',
    noResultsTitle: '尚未生成发型',
    noResultsDesc: '请在左侧上传照片并选择发型，即可在此查看效果。',
    noFavoritesDesc: '暂无收藏发型。点击结果上的爱心图标即可收藏！',
    resultLabel: '效果预览',
    compareLabel: '原图 / 效果图',
    compareTip: '拖动滑块对比效果',
    downloadBtn: '下载图片',
    randomLabel: '神秘发型',
    randomDesc: '由 AI 随机生成的独一无二发型。',
    tabPresets: '预设模版',
    tabCustom: '文字描述',
    tabReference: '参考图片',
    customPromptPlaceholder: '描述你想要的发型... 例如：“带有刘海的红色短卷发” 或 “赛博朋克风格的霓虹色刺猬头”',
    customPromptLabel: '发型描述',
    refImageLabel: '上传参考图片',
    refImageDesc: '上传一张包含你想要发型的照片。',
    refImageBtn: '选择参考图',
    viewResults: '查看最新',
    viewFavorites: '查看收藏',
  }
};
